#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Convert 'uitleg vaardigheden.docx' to interactive HTML with sidebar navigation.
Usage: python convert_vaardigheden.py [paragraph_folder_path]
       python convert_vaardigheden.py --all   (processes all paragraphs)

HOW TO ADAPT
============
This script reads the standard vaardigheden Word template (as generated by
econ-word-templates Template A) and produces a self-contained HTML page with:
- Sticky sidebar with section navigation + domain badges
- IntersectionObserver active-state tracking
- Hero header with preview cards
- Per-section: begrippen tables, formula boxes, voorbeeld boxes, callouts
- Interactive checklist
- Responsive mobile menu

Domain color mapping can be extended in DOMAIN_MAP below.
"""
import sys, io, os, glob, html as html_mod
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from docx import Document

# ═══════════════════════════════════════════════════════════
# Domain → color mapping
# ═══════════════════════════════════════════════════════════
DOMAIN_MAP = {
    'Wiskundig':        ('wiskunde',   '#1A5276', '#EBF5FB', '#154360'),
    'Economisch':       ('economisch', '#E67E22', '#FEF5E7', '#BA6A1C'),
    'Grafisch':         ('grafisch',   '#1E8449', '#E8F8F0', '#186A3B'),
    'Bedrijfseconomie': ('bedrijf',    '#E67E22', '#FEF5E7', '#BA6A1C'),
    'Marktanalyse':     ('markt',      '#1A5276', '#EBF5FB', '#154360'),
    'Marktwerking':     ('marktwerk',  '#1A5276', '#EBF5FB', '#154360'),
    'Overheidsbeleid':  ('overheid',   '#1E8449', '#E8F8F0', '#186A3B'),
    'Arbeidsmarkt':     ('arbeids',    '#E67E22', '#FEF5E7', '#BA6A1C'),
    'Externe effecten': ('extern',     '#1E8449', '#E8F8F0', '#186A3B'),
}

def get_domain_info(domain_name):
    """Return (css_class, primary, light, dark) for a domain name."""
    if domain_name in DOMAIN_MAP:
        return DOMAIN_MAP[domain_name]
    # Fallback: blue
    slug = domain_name.lower().replace(' ', '')[:8]
    return (slug, '#1A5276', '#EBF5FB', '#154360')

def esc(text):
    """HTML-escape text."""
    return html_mod.escape(text)

def parse_document(docx_path):
    """Parse a voorkennis .docx and return structured data."""
    doc = Document(docx_path)

    # Extract title and subtitle from first paragraphs
    title = ''
    subtitle = ''
    for p in doc.paragraphs[:5]:
        t = p.text.strip()
        if t and not title:
            title = t
        elif t and title and not subtitle:
            subtitle = t
            break

    # Find inhoudsopgave table (Nr. / Onderwerp / Omschrijving / Domein)
    sections_meta = []
    for table in doc.tables:
        if len(table.rows) > 1 and len(table.columns) >= 4:
            if table.rows[0].cells[0].text.strip() == 'Nr.':
                for row in table.rows[1:]:
                    sections_meta.append({
                        'nr': row.cells[0].text.strip(),
                        'onderwerp': row.cells[1].text.strip(),
                        'omschrijving': row.cells[2].text.strip(),
                        'domein': row.cells[3].text.strip(),
                    })
                break

    # Now parse content per section
    # Sections are delimited by section-header tables (1 row, 2 cols, first cell is digit)
    all_elements = []  # flat list of (type, data)

    for i, table in enumerate(doc.tables):
        # Section header table
        if len(table.rows) == 1 and len(table.columns) == 2:
            first_cell = table.rows[0].cells[0].text.strip()
            second_cell = table.rows[0].cells[1].text.strip()
            if first_cell.isdigit() and '\n' in second_cell:
                parts = second_cell.split('\n')
                all_elements.append(('section_header', {
                    'nr': first_cell,
                    'title': parts[0].strip(),
                    'domain': parts[-1].strip() if len(parts) > 1 else '',
                }))
                continue

        # Begrippen table (has "Begrip" and "Betekenis" headers)
        if len(table.rows) > 1 and len(table.columns) == 2:
            h0 = table.rows[0].cells[0].text.strip()
            h1 = table.rows[0].cells[1].text.strip()
            if h0 == 'Begrip' and h1 == 'Betekenis':
                rows = []
                for row in table.rows[1:]:
                    rows.append((row.cells[0].text.strip(), row.cells[1].text.strip()))
                all_elements.append(('begrippen', rows))
                continue

        # Samenvatting table (first cell contains 📋 or "Samenvatting")
        if len(table.rows) > 1 and len(table.columns) == 2:
            h0 = table.rows[0].cells[0].text.strip()
            if '📋' in h0 or 'Samenvatting' in h0:
                rows = []
                for row in table.rows[1:]:
                    rows.append((row.cells[0].text.strip(), row.cells[1].text.strip()))
                all_elements.append(('samenvatting', rows))
                continue

        # Single-cell tables: callouts or formula boxes
        if len(table.rows) == 1 and len(table.columns) == 1:
            text = table.rows[0].cells[0].text.strip()
            if text.startswith('⭐') or text.startswith('Kernregel'):
                all_elements.append(('callout_kernregel', text))
            elif text.startswith('⚠') or text.startswith('Let op'):
                all_elements.append(('callout_letop', text))
            elif text.startswith('✅') or text.startswith('Controle'):
                all_elements.append(('callout_controle', text))
            elif text.startswith('✨') or text.startswith('Tip'):
                all_elements.append(('callout_tip', text))
            else:
                all_elements.append(('formula_box', text))
            continue

    # Parse paragraphs for headings and text
    para_elements = []
    for p in doc.paragraphs:
        text = p.text.strip()
        if not text:
            continue
        style = p.style.name if p.style else ''
        if style == 'Heading 1':
            para_elements.append(('heading1', text))
        elif style == 'Heading 2':
            para_elements.append(('heading2', text))
        elif style == 'List Paragraph':
            para_elements.append(('list_item', text))
        else:
            # Skip title/subtitle (already captured)
            para_elements.append(('paragraph', text))

    # Now merge tables and paragraphs into sections
    # Strategy: walk through paragraphs, and when we encounter section content,
    # interleave the tables at the right positions
    sections = []
    current_section = None

    # Build section content by matching heading2 patterns between section headers
    section_boundaries = []
    for i, (etype, edata) in enumerate(all_elements):
        if etype == 'section_header':
            section_boundaries.append(i)

    # Group all_elements by section
    for idx, sb_idx in enumerate(section_boundaries):
        header = all_elements[sb_idx][1]
        next_sb = section_boundaries[idx + 1] if idx + 1 < len(section_boundaries) else len(all_elements)

        section = {
            'nr': header['nr'],
            'title': header['title'],
            'domain': header['domain'],
            'elements': []
        }

        for j in range(sb_idx + 1, next_sb):
            section['elements'].append(all_elements[j])

        sections.append(section)

    # Extract checklist items from paragraphs
    checklist = []
    in_checklist = False
    for etype, edata in para_elements:
        if etype == 'heading1' and 'Checklist' in edata:
            in_checklist = True
            continue
        if in_checklist and etype == 'list_item':
            checklist.append(edata)
        elif in_checklist and etype == 'heading1':
            break

    # Extract sub-headings and text per section from paragraphs
    # We need to associate paragraph content with sections
    # Find paragraph content between section-related headings
    section_para_content = {s['nr']: [] for s in sections}
    current_sec_nr = None

    for etype, edata in para_elements:
        if etype == 'heading2':
            # Check if this heading belongs to a section
            for s in sections:
                # Match by checking if heading appears in section context
                pass
            if current_sec_nr:
                section_para_content[current_sec_nr].append(('heading2', edata))
        elif etype == 'paragraph' and current_sec_nr:
            section_para_content[current_sec_nr].append(('paragraph', edata))

    # Simpler approach: rebuild sections by walking all doc elements in order
    # Use section header tables as delimiters
    return {
        'title': title,
        'subtitle': subtitle,
        'sections_meta': sections_meta,
        'sections': sections,
        'checklist': checklist,
        'all_elements': all_elements,
        'para_elements': para_elements,
    }


def build_sections_from_doc(docx_path):
    """Parse document and build complete section data with interleaved content."""
    doc = Document(docx_path)

    title = ''
    subtitle = ''
    for p in doc.paragraphs[:5]:
        t = p.text.strip()
        if t and not title:
            title = t
        elif t and title and not subtitle:
            subtitle = t
            break

    # Find inhoudsopgave
    sections_meta = []
    for table in doc.tables:
        if len(table.rows) > 1 and len(table.columns) >= 4:
            if table.rows[0].cells[0].text.strip() == 'Nr.':
                for row in table.rows[1:]:
                    sections_meta.append({
                        'nr': row.cells[0].text.strip(),
                        'onderwerp': row.cells[1].text.strip(),
                        'domein': row.cells[3].text.strip(),
                    })
                break

    # Collect TOC list items (for fallback section header detection)
    toc_items = []
    in_toc = False
    for p in doc.paragraphs:
        style = p.style.name if p.style else ''
        text = p.text.strip()
        if style == 'Heading 1' and 'Inhoudsopgave' in text:
            in_toc = True
            continue
        if in_toc and style == 'List Paragraph' and text:
            toc_items.append(text)
        elif in_toc and style == 'Heading 1':
            in_toc = False
    toc_set = set(toc_items)

    # Build a unified stream of elements (paragraphs + tables in document order)
    from docx.oxml.ns import qn
    body = doc.element.body

    stream = []
    table_index = 0
    para_index = 0
    has_standard_section_headers = False  # track if we find 1×2 section headers

    for child in body:
        tag = child.tag.split('}')[-1] if '}' in child.tag else child.tag
        if tag == 'p':
            if para_index < len(doc.paragraphs):
                p = doc.paragraphs[para_index]
                para_index += 1
                text = p.text.strip()
                if not text:
                    continue
                style = p.style.name if p.style else ''
                if style == 'Heading 1':
                    stream.append(('heading1', text))
                elif style == 'Heading 2':
                    stream.append(('heading2', text))
                elif style == 'List Paragraph':
                    stream.append(('list_item', text))
                else:
                    stream.append(('paragraph', text))
        elif tag == 'tbl':
            if table_index < len(doc.tables):
                table = doc.tables[table_index]
                table_index += 1

                nrows = len(table.rows)
                ncols = len(table.columns)

                # Section header (1×2, first cell is digit)
                if nrows == 1 and ncols == 2:
                    first = table.rows[0].cells[0].text.strip()
                    second = table.rows[0].cells[1].text.strip()
                    if first.isdigit() and '\n' in second:
                        parts = second.split('\n')
                        stream.append(('section_header', {
                            'nr': first,
                            'title': parts[0].strip(),
                            'domain': parts[-1].strip(),
                        }))
                        has_standard_section_headers = True
                        continue

                # Domain badges (1×3, skip)
                if nrows == 1 and ncols == 3:
                    continue

                # Inhoudsopgave (already parsed)
                if nrows > 1 and ncols >= 4:
                    if table.rows[0].cells[0].text.strip() == 'Nr.':
                        continue

                # Begrippen table
                if nrows > 1 and ncols == 2:
                    h0 = table.rows[0].cells[0].text.strip()
                    h1 = table.rows[0].cells[1].text.strip()
                    if h0 == 'Begrip' and h1 == 'Betekenis':
                        rows = [(r.cells[0].text.strip(), r.cells[1].text.strip()) for r in table.rows[1:]]
                        stream.append(('begrippen', rows))
                        continue
                    # Samenvatting
                    if '📋' in h0 or 'Samenvatting' in h0:
                        rows = [(r.cells[0].text.strip(), r.cells[1].text.strip()) for r in table.rows[1:]]
                        stream.append(('samenvatting', rows))
                        continue

                # Single-cell tables
                if nrows == 1 and ncols == 1:
                    text = table.rows[0].cells[0].text.strip()
                    if text.startswith('⭐'):
                        stream.append(('callout_kernregel', text))
                    elif text.startswith('⚠'):
                        stream.append(('callout_letop', text))
                    elif text.startswith('✅'):
                        stream.append(('callout_controle', text))
                    elif text.startswith('✨'):
                        stream.append(('callout_tip', text))
                    elif text in toc_set:
                        # Fallback section header (Toepassen docs)
                        stream.append(('section_header_simple', text))
                    else:
                        stream.append(('formula_box', text))
                    continue

                # Other tables: treat as generic
                stream.append(('generic_table', table))

    # Now split stream into sections
    sections = []
    current = None
    checklist = []
    valkuilen = []
    in_checklist = False
    in_valkuilen = False
    simple_section_counter = 0

    for etype, edata in stream:
        if etype == 'section_header':
            if current:
                sections.append(current)
            current = {
                'nr': edata['nr'],
                'title': edata['title'],
                'domain': edata['domain'],
                'content': [],
            }
            in_checklist = False
            in_valkuilen = False
            continue

        if etype == 'section_header_simple':
            if current:
                sections.append(current)
            simple_section_counter += 1
            current = {
                'nr': str(simple_section_counter),
                'title': edata,
                'domain': 'Economisch',
                'content': [],
            }
            in_checklist = False
            in_valkuilen = False
            continue

        if etype == 'heading1' and 'valkuil' in edata.lower():
            if current:
                sections.append(current)
                current = None
            in_valkuilen = True
            in_checklist = False
            continue

        if etype == 'heading1' and ('Checklist' in edata or 'checklist' in edata or 'Samenvatting' in edata):
            if current:
                sections.append(current)
                current = None
            in_checklist = True
            in_valkuilen = False
            continue

        if in_valkuilen:
            if etype in ('callout_letop', 'callout_kernregel', 'callout_controle', 'callout_tip'):
                valkuilen.append((etype, edata))
            continue

        if in_checklist and etype == 'list_item':
            checklist.append(edata)
            continue

        if current:
            current['content'].append((etype, edata))

    if current:
        sections.append(current)

    # If no sections_meta was found (no standard inhoudsopgave table), build from sections
    if not sections_meta and sections:
        for s in sections:
            sections_meta.append({
                'nr': s['nr'],
                'onderwerp': s['title'],
                'domein': s['domain'],
            })

    return {
        'title': title,
        'subtitle': subtitle,
        'sections_meta': sections_meta,
        'sections': sections,
        'checklist': checklist,
        'valkuilen': valkuilen,
    }


def render_callout(callout_type, text):
    """Render a callout box."""
    # Strip emoji prefix
    clean = text
    for prefix in ['⭐ ', '⚠ ', '✅ ', '✨ ', '⭐', '⚠', '✅', '✨']:
        if clean.startswith(prefix):
            clean = clean[len(prefix):].strip()
            break

    # Split into label and content
    if ':' in clean:
        label, content = clean.split(':', 1)
        label = label.strip()
        content = content.strip()
    else:
        label = {'callout_kernregel': 'Kernregel', 'callout_letop': 'Let op',
                 'callout_controle': 'Controle', 'callout_tip': 'Tip'}[callout_type]
        content = clean

    icons = {
        'callout_kernregel': '&#11088;',
        'callout_letop': '&#9888;&#65039;',
        'callout_controle': '&#9989;',
        'callout_tip': '&#10024;',
    }
    css = {
        'callout_kernregel': 'callout-kernregel',
        'callout_letop': 'callout-letop',
        'callout_controle': 'callout-controle',
        'callout_tip': 'callout-tip',
    }

    return f'''        <div class="callout {css[callout_type]}">
          <span class="callout-icon">{icons[callout_type]}</span>
          <strong>{esc(label)}:</strong> {esc(content)}
        </div>
'''


def generate_html(data, para_number, para_name):
    """Generate the full HTML string."""
    sections = data['sections']
    checklist = data['checklist']

    # Collect unique domains for CSS variables
    domain_infos = {}
    for s in sections:
        di = get_domain_info(s['domain'])
        domain_infos[di[0]] = di

    # Build CSS variables for domains
    css_vars = ''
    for cls, (_, primary, light, dark) in domain_infos.items():
        css_vars += f'    --{cls}-primary: {primary};\n'
        css_vars += f'    --{cls}-light: {light};\n'
        css_vars += f'    --{cls}-dark: {dark};\n'

    # Hero gradient
    domain_classes = [get_domain_info(s['domain'])[0] for s in sections]
    unique_domains_ordered = list(dict.fromkeys(domain_classes))
    if len(unique_domains_ordered) == 1:
        hero_gradient = f'var(--{unique_domains_ordered[0]}-primary)'
    else:
        pct = 100 / len(unique_domains_ordered)
        parts = []
        for i, d in enumerate(unique_domains_ordered):
            parts.append(f'var(--{d}-primary) {pct*i:.0f}% {pct*(i+1):.0f}%')
        hero_gradient = f'linear-gradient(90deg, {", ".join(parts)})'

    # Build domain CSS classes
    domain_css_blocks = ''
    for cls in domain_infos:
        domain_css_blocks += f'  .nav-item.active.domain-{cls} {{ border-left-color: var(--{cls}-primary); }}\n'
        domain_css_blocks += f'  .domain-{cls} .nav-number {{ background: var(--{cls}-primary); }}\n'
        domain_css_blocks += f'  .domain-{cls} .nav-badge {{ background: var(--{cls}-light); color: var(--{cls}-primary); }}\n'
        domain_css_blocks += f'  .section-header.border-{cls} {{ border-bottom: 3px solid var(--{cls}-primary); }}\n'
        domain_css_blocks += f'  .section-num.bg-{cls} {{ background: var(--{cls}-primary); }}\n'
        domain_css_blocks += f'  .badge-{cls} {{ background: var(--{cls}-light); color: var(--{cls}-primary); }}\n'
        domain_css_blocks += f'  .samenvatting-table caption.caption-{cls} {{ background: var(--{cls}-primary); }}\n'
        domain_css_blocks += f'  .hero-card.card-{cls} {{ border-top-color: var(--{cls}-primary); }}\n'
        domain_css_blocks += f'  .card-{cls} .hero-card-domain {{ background: rgba(0,0,0,0.15); color: var(--{cls}-light); }}\n'

    # Build sidebar nav items
    sidebar_items = ''
    for s in sections:
        dcls = get_domain_info(s['domain'])[0]
        sidebar_items += f'''    <a class="nav-item domain-{dcls}" href="#sectie-{s['nr']}" data-section="sectie-{s['nr']}">
      <span class="nav-number">{s['nr']}</span>
      <span class="nav-text">
        <span class="nav-title">{esc(s['title'])}</span>
        <span class="nav-badge">{esc(s['domain'])}</span>
      </span>
    </a>
'''

    # Build hero cards
    hero_cards = ''
    for s in sections:
        dcls = get_domain_info(s['domain'])[0]
        hero_cards += f'''          <div class="hero-card card-{dcls}" data-target="sectie-{s['nr']}">
            <div class="hero-card-num">{s['nr'].zfill(2)}</div>
            <div class="hero-card-title">{esc(s['title'])}</div>
            <span class="hero-card-domain">{esc(s['domain'])}</span>
          </div>
'''

    # Build section content
    sections_html = ''
    for s in sections:
        dcls = get_domain_info(s['domain'])[0]

        content_html = ''
        for etype, edata in s['content']:
            if etype == 'heading2':
                content_html += f'        <h3 class="sub-heading">{esc(edata)}</h3>\n'
            elif etype == 'paragraph':
                # Skip title-like paragraphs that repeat section info
                if edata == data['title'] or edata == data['subtitle']:
                    continue
                content_html += f'        <p class="intro-text">{esc(edata)}</p>\n'
            elif etype == 'begrippen':
                content_html += '        <table class="begrippen-table">\n'
                content_html += '          <thead><tr><th>Begrip</th><th>Betekenis</th></tr></thead>\n'
                content_html += '          <tbody>\n'
                for term, meaning in edata:
                    content_html += f'            <tr><td>{esc(term)}</td><td>{esc(meaning)}</td></tr>\n'
                content_html += '          </tbody>\n        </table>\n'
            elif etype == 'formula_box':
                lines = edata.replace('\n', '<br>\n            ')
                content_html += f'        <div class="formula-box">\n            {lines}\n        </div>\n'
            elif etype in ('callout_kernregel', 'callout_letop', 'callout_controle', 'callout_tip'):
                content_html += render_callout(etype, edata)
            elif etype == 'samenvatting':
                content_html += f'        <table class="samenvatting-table">\n'
                content_html += f'          <caption class="caption-{dcls}">&#128203; Samenvatting</caption>\n'
                content_html += '          <tbody>\n'
                for label, value in edata:
                    content_html += f'            <tr><td>{esc(label)}</td><td>{esc(value)}</td></tr>\n'
                content_html += '          </tbody>\n        </table>\n'

        sections_html += f'''
      <section class="section" id="sectie-{s['nr']}">
        <div class="section-header border-{dcls}">
          <span class="section-num bg-{dcls}">{s['nr']}</span>
          <div class="section-title-group">
            <div class="section-title">{esc(s['title'])}</div>
            <span class="section-badge badge-{dcls}">{esc(s['domain'])}</span>
          </div>
        </div>
{content_html}
      </section>
'''

    # Valkuilen
    valkuilen_html = ''
    valkuilen = data.get('valkuilen', [])
    if valkuilen:
        valk_items = ''
        for vtype, vtext in valkuilen:
            valk_items += render_callout(vtype, vtext)
        valkuilen_html = f'''
      <div class="checklist-section" style="margin-bottom: 2rem;">
        <div class="checklist-title">Veelvoorkomende valkuilen</div>
        <p class="checklist-sub">Let op deze veelgemaakte fouten bij het leren van deze paragraaf:</p>
{valk_items}
      </div>
'''

    # Checklist
    checklist_html = ''
    if checklist:
        items = ''
        for i, item in enumerate(checklist, 1):
            items += f'''        <div class="checklist-item">
          <input type="checkbox" id="check{i}">
          <label for="check{i}">{esc(item)}</label>
        </div>
'''
        checklist_html = f'''
      <div class="checklist-section">
        <div class="checklist-title">Samenvatting checklist</div>
        <p class="checklist-sub">Controleer of je de volgende vaardigheden beheerst:</p>
{items}
      </div>
'''

    # Grid columns for hero cards
    n = len(sections)
    grid_cols = f'repeat({n}, 1fr)' if n <= 5 else f'repeat({min(n,4)}, 1fr)'

    # Assemble full HTML
    return f'''<!DOCTYPE html>
<html lang="nl">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{para_number} {esc(para_name)} – Uitleg vaardigheden</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    font-family: Arial, sans-serif;
    background: #F7F8FA;
    color: #2D3748;
    line-height: 1.6;
    min-height: 100vh;
  }}
  a {{ color: inherit; text-decoration: none; }}

  :root {{
    --navy: #1E2761;
    --dark: #2D3748;
    --gray: #718096;
    --light-gray: #F7F8FA;
    --border-gray: #CBD5E0;
    --white: #FFFFFF;
    --sidebar-w: 260px;
{css_vars}  }}

  .page-layout {{ display: flex; min-height: 100vh; }}

  .sidebar {{
    width: var(--sidebar-w); flex-shrink: 0;
    background: var(--white); border-right: 1px solid var(--border-gray);
    position: sticky; top: 0; height: 100vh; overflow-y: auto;
    padding: 1.2rem 0; z-index: 10;
  }}
  .sidebar-header {{
    padding: 0.6rem 1.2rem 1rem;
    border-bottom: 1px solid var(--border-gray);
    margin-bottom: 0.6rem;
  }}
  .sidebar-header h2 {{ font-size: 0.82rem; font-weight: bold; color: var(--navy); line-height: 1.3; }}
  .sidebar-header p {{ font-size: 0.7rem; color: var(--gray); margin-top: 0.2rem; }}

  .nav-item {{
    display: flex; align-items: flex-start; gap: 0.6rem;
    padding: 0.65rem 1.2rem; cursor: pointer;
    border-left: 3px solid transparent;
    transition: background 0.15s, border-color 0.15s;
  }}
  .nav-item:hover {{ background: #F7FAFC; }}
  .nav-item.active {{ background: var(--light-gray); font-weight: bold; }}
{domain_css_blocks}
  .nav-number {{
    display: inline-flex; align-items: center; justify-content: center;
    width: 22px; height: 22px; border-radius: 50%;
    font-size: 0.7rem; font-weight: bold; color: var(--white); flex-shrink: 0;
    margin-top: 1px;
  }}
  .nav-text {{ flex: 1; min-width: 0; }}
  .nav-title {{ font-size: 0.76rem; color: var(--dark); line-height: 1.3; display: block; }}
  .nav-badge {{
    display: inline-block; font-size: 0.6rem; font-weight: bold;
    padding: 0.1rem 0.45rem; border-radius: 3px; margin-top: 0.2rem;
    text-transform: uppercase; letter-spacing: 0.03em;
  }}

  .sidebar-toggle {{
    display: none; position: fixed; top: 0.75rem; left: 0.75rem; z-index: 20;
    width: 36px; height: 36px; border-radius: 6px; border: 1px solid var(--border-gray);
    background: var(--white); cursor: pointer;
    align-items: center; justify-content: center;
    box-shadow: 0 1px 4px rgba(0,0,0,0.08);
  }}
  .sidebar-toggle svg {{ width: 20px; height: 20px; stroke: var(--dark); stroke-width: 2; fill: none; }}
  .sidebar-overlay {{ display: none; position: fixed; inset: 0; background: rgba(0,0,0,0.3); z-index: 9; }}

  .content {{ flex: 1; min-width: 0; }}

  .hero {{
    background: var(--navy); color: var(--white);
    padding: 2.5rem 2rem 1.8rem; position: relative;
  }}
  .hero::before {{
    content: ""; position: absolute; top: 0; left: 0; right: 0;
    height: 5px; background: {hero_gradient};
  }}
  .hero-inner {{ max-width: 860px; margin: 0 auto; }}
  .hero-badge {{
    display: inline-block; background: rgba(255,255,255,0.12);
    border: 1px solid rgba(255,255,255,0.2); padding: 0.25rem 0.85rem;
    border-radius: 4px; font-size: 0.85rem; color: rgba(255,255,255,0.85);
  }}
  .hero h1 {{ font-size: 2.1rem; font-weight: bold; margin: 0.6rem 0 0.3rem; }}
  .hero-sub {{ font-size: 0.95rem; color: rgba(255,255,255,0.65); }}

  .hero-cards {{
    display: grid; grid-template-columns: {grid_cols}; gap: 0.8rem;
    margin-top: 1.5rem;
  }}
  .hero-card {{
    background: rgba(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.12);
    border-radius: 8px; padding: 0.9rem; cursor: pointer;
    transition: background 0.15s, transform 0.15s;
    border-top: 3px solid transparent;
  }}
  .hero-card:hover {{ background: rgba(255,255,255,0.14); transform: translateY(-2px); }}
  .hero-card-num {{ font-size: 0.7rem; font-weight: bold; opacity: 0.6; margin-bottom: 0.3rem; }}
  .hero-card-title {{ font-size: 0.82rem; font-weight: bold; line-height: 1.3; }}
  .hero-card-domain {{
    display: inline-block; font-size: 0.6rem; padding: 0.1rem 0.4rem;
    border-radius: 3px; margin-top: 0.4rem; text-transform: uppercase;
    letter-spacing: 0.03em;
  }}

  main {{ max-width: 860px; margin: 0 auto; padding: 1.5rem 2rem 3rem; }}

  .section {{ margin-bottom: 3rem; scroll-margin-top: 1rem; }}
  .section-header {{
    display: flex; align-items: center; gap: 0.7rem;
    padding-bottom: 0.7rem; margin-bottom: 1.2rem;
  }}
  .section-num {{
    display: inline-flex; align-items: center; justify-content: center;
    width: 34px; height: 34px; border-radius: 50%;
    font-size: 0.95rem; font-weight: bold; color: var(--white); flex-shrink: 0;
  }}
  .section-title-group {{ flex: 1; }}
  .section-title {{ font-size: 1.25rem; font-weight: bold; color: var(--dark); }}
  .section-badge {{
    display: inline-block; font-size: 0.65rem; font-weight: bold;
    padding: 0.15rem 0.55rem; border-radius: 3px; margin-top: 0.15rem;
    text-transform: uppercase; letter-spacing: 0.03em;
  }}

  .sub-heading {{
    font-size: 1.05rem; font-weight: bold; color: var(--dark);
    margin: 1.6rem 0 0.6rem; padding-left: 0.1rem;
  }}
  .intro-text {{ font-size: 0.92rem; color: var(--gray); margin-bottom: 1rem; line-height: 1.7; }}

  .begrippen-table {{ width: 100%; border-collapse: collapse; margin-bottom: 1.2rem; font-size: 0.88rem; }}
  .begrippen-table th {{
    text-align: left; font-weight: bold; padding: 0.55rem 0.8rem;
    border-bottom: 2px solid var(--border-gray); color: var(--dark);
    font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.03em;
  }}
  .begrippen-table td {{ padding: 0.55rem 0.8rem; border-bottom: 1px solid #EDF2F7; vertical-align: top; }}
  .begrippen-table tr:last-child td {{ border-bottom: none; }}
  .begrippen-table td:first-child {{ font-weight: 600; color: var(--dark); }}
  .begrippen-table td:last-child {{ color: #4A5568; }}

  .formula-box {{
    background: #F8F9FA; border: 1px solid #E2E8F0; border-radius: 6px;
    padding: 1rem 1.2rem; margin-bottom: 1rem;
    font-family: Consolas, 'Courier New', monospace; font-size: 0.88rem;
    line-height: 1.8; color: var(--dark); border-left: 4px solid #A0AEC0;
  }}

  .callout {{
    border-radius: 6px; padding: 0.85rem 1rem; margin-bottom: 0.8rem;
    font-size: 0.88rem; line-height: 1.6;
  }}
  .callout-kernregel {{ background: #FFF8E1; border-left: 4px solid #F9A825; color: #5D4037; }}
  .callout-letop {{ background: #FFF3E0; border-left: 4px solid #EF6C00; color: #BF360C; }}
  .callout-controle {{ background: #E8F5E9; border-left: 4px solid #43A047; color: #1B5E20; }}
  .callout-tip {{ background: #EBF5FB; border-left: 4px solid #1A5276; color: #154360; }}
  .callout-icon {{ margin-right: 0.4rem; }}

  .samenvatting-table {{
    width: 100%; border-collapse: collapse; margin-bottom: 1.2rem;
    font-size: 0.88rem; background: var(--white);
    border-radius: 6px; overflow: hidden; border: 1px solid #E2E8F0;
  }}
  .samenvatting-table caption {{
    text-align: left; font-weight: bold; font-size: 0.82rem;
    padding: 0.6rem 0.8rem; color: var(--white);
  }}
  .samenvatting-table td {{ padding: 0.5rem 0.8rem; border-bottom: 1px solid #EDF2F7; vertical-align: top; }}
  .samenvatting-table tr:last-child td {{ border-bottom: none; }}
  .samenvatting-table td:first-child {{ font-weight: 600; color: var(--dark); width: 30%; }}

  .checklist-section {{
    background: var(--white); border: 1px solid var(--border-gray);
    border-radius: 8px; padding: 1.5rem; margin-top: 2rem;
  }}
  .checklist-title {{ font-size: 1.1rem; font-weight: bold; color: var(--dark); margin-bottom: 0.3rem; }}
  .checklist-sub {{ font-size: 0.85rem; color: var(--gray); margin-bottom: 1rem; }}
  .checklist-item {{
    display: flex; align-items: flex-start; gap: 0.6rem;
    padding: 0.5rem 0; border-bottom: 1px solid #EDF2F7;
    font-size: 0.88rem; color: var(--dark); cursor: pointer; user-select: none;
  }}
  .checklist-item:last-child {{ border-bottom: none; }}
  .checklist-item input[type="checkbox"] {{
    width: 18px; height: 18px; margin-top: 1px; flex-shrink: 0;
    accent-color: #1E8449; cursor: pointer;
  }}
  .checklist-item.checked label {{ color: var(--gray); text-decoration: line-through; }}

  @media (max-width: 1024px) {{
    .hero-cards {{ grid-template-columns: repeat(2, 1fr); }}
  }}
  @media (max-width: 768px) {{
    .sidebar {{
      position: fixed; left: -280px; top: 0; height: 100vh; width: 280px;
      transition: left 0.25s ease; box-shadow: 2px 0 8px rgba(0,0,0,0.1);
    }}
    .sidebar.open {{ left: 0; }}
    .sidebar-toggle {{ display: flex; }}
    .sidebar-overlay.show {{ display: block; }}
    .hero {{ padding: 2rem 1.2rem 1.5rem; }}
    .hero h1 {{ font-size: 1.6rem; }}
    .hero-cards {{ grid-template-columns: 1fr 1fr; gap: 0.6rem; }}
    main {{ padding: 1rem 1.2rem 2rem; }}
    .section-title {{ font-size: 1.1rem; }}
  }}
  @media (max-width: 480px) {{
    .hero-cards {{ grid-template-columns: 1fr; }}
  }}
</style>
</head>
<body>

<button class="sidebar-toggle" id="sidebarToggle" aria-label="Menu openen">
  <svg viewBox="0 0 24 24"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>
</button>
<div class="sidebar-overlay" id="sidebarOverlay"></div>

<div class="page-layout">
  <nav class="sidebar" id="sidebar">
    <div class="sidebar-header">
      <h2>{para_number} {esc(para_name)}</h2>
      <p>Uitleg vaardigheden</p>
    </div>
{sidebar_items}
  </nav>

  <div class="content">
    <header class="hero">
      <div class="hero-inner">
        <span class="hero-badge">{para_number} &middot; Vaardigheden</span>
        <h1>{esc(para_name)} &mdash; Vaardigheden</h1>
        <p class="hero-sub">{esc(data['subtitle'])}</p>
        <div class="hero-cards">
{hero_cards}
        </div>
      </div>
    </header>

    <main>
{sections_html}
{valkuilen_html}
{checklist_html}
    </main>
  </div>
</div>

<script>
(function() {{
  document.querySelectorAll('[data-section], [data-target]').forEach(function(el) {{
    el.addEventListener('click', function(e) {{
      var id = el.dataset.section || el.dataset.target;
      var target = document.getElementById(id);
      if (target) {{
        e.preventDefault();
        target.scrollIntoView({{ behavior: 'smooth', block: 'start' }});
        sidebar.classList.remove('open');
        overlay.classList.remove('show');
      }}
    }});
  }});

  var navItems = document.querySelectorAll('.nav-item[data-section]');
  var sections = document.querySelectorAll('.section');
  var observer = new IntersectionObserver(function(entries) {{
    entries.forEach(function(entry) {{
      if (entry.isIntersecting) {{
        navItems.forEach(function(n) {{ n.classList.remove('active'); }});
        var active = document.querySelector('.nav-item[data-section="' + entry.target.id + '"]');
        if (active) active.classList.add('active');
      }}
    }});
  }}, {{ rootMargin: '-10% 0px -80% 0px' }});
  sections.forEach(function(s) {{ observer.observe(s); }});

  var sidebar = document.getElementById('sidebar');
  var overlay = document.getElementById('sidebarOverlay');
  var toggle = document.getElementById('sidebarToggle');
  toggle.addEventListener('click', function() {{
    sidebar.classList.toggle('open');
    overlay.classList.toggle('show');
  }});
  overlay.addEventListener('click', function() {{
    sidebar.classList.remove('open');
    overlay.classList.remove('show');
  }});

  document.querySelectorAll('.checklist-item input').forEach(function(cb) {{
    cb.addEventListener('change', function() {{
      this.closest('.checklist-item').classList.toggle('checked', this.checked);
    }});
  }});
}})();
</script>
</body>
</html>'''


def find_paragraph_info(folder_path):
    """Extract paragraph number and name from folder path."""
    # Folder name like "3.2.4 Paragraaf 4 - Oligopolie"
    basename = os.path.basename(folder_path.rstrip('/\\'))
    # Extract number (e.g., "3.2.4")
    parts = basename.split(' ', 1)
    number = parts[0]
    # Extract name after " - "
    if ' - ' in basename:
        name = basename.split(' - ', 1)[1]
    else:
        name = parts[1] if len(parts) > 1 else basename
    return number, name


def process_paragraph(para_folder):
    """Process a single paragraph folder."""
    para_number, para_name = find_paragraph_info(para_folder)

    # Find the vaardigheden docx
    pattern = os.path.join(para_folder, '2. Leren', '*vaardigheden*.docx')
    files = glob.glob(pattern)
    if not files:
        print(f'  SKIP {para_number}: no vaardigheden.docx found')
        return False

    docx_path = files[0]

    try:
        data = build_sections_from_doc(docx_path)
    except Exception as e:
        print(f'  ERROR {para_number}: {e}')
        return False

    if not data['sections']:
        print(f'  SKIP {para_number}: no sections found')
        return False

    html_content = generate_html(data, para_number, para_name)

    # Write HTML file
    html_filename = f'{para_number} {para_name} \u2013 uitleg vaardigheden.html'
    html_path = os.path.join(para_folder, '2. Leren', html_filename)

    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(html_content)

    print(f'  OK {para_number} {para_name} ({len(data["sections"])} sections, {len(data["checklist"])} checklist items)')
    return True


def main():
    if len(sys.argv) < 2:
        print('Usage: python convert_voorkennis.py [path] or --all')
        sys.exit(1)

    if sys.argv[1] == '--all':
        # Find all paragraph folders
        base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        folders = sorted(glob.glob(os.path.join(base, '3.*/3.*.*')))

        print(f'Found {len(folders)} paragraph folders')
        success = 0
        for folder in folders:
            if os.path.isdir(folder):
                if process_paragraph(folder):
                    success += 1
        print(f'\nDone: {success}/{len(folders)} converted')
    else:
        process_paragraph(sys.argv[1])


if __name__ == '__main__':
    main()
